version: '3.8'

networks:
  broker-net:
volumes:
  prometheus_data:
  postgres:

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=broker
    volumes:
      - postgres:/data/postgresports
    ports:
      - 5434:5432
    networks:
      - broker-net

  cassandra:
    image: cassandra
    ports:
      - 9042:9042
    networks:
      - broker-net

  broker:
    build: .
    ports:
      - 8080:8080
      - 9091:9091
    depends_on:
      - postgres
    networks:
      - broker-net
    restart: always

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=20d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - broker-net
    restart: always

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    volumes:
      - ../grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=testtest
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - 3000:3000
    networks:
      - broker-net

    restart: always



