apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    name: grafana-service
    app: message-grafana
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30010
  selector:
    name: grafana-pod
    app: message-broker