apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    name: postgres-deployment
    app: message-broker
spec:
  selector:
    matchLabels:
      name: postgres-pod
      app: message-broker
  replicas: 1
  template:
    metadata:
      name: postgres-pod
      app: message-broker
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: broker