apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    name: prometheus-service
    app: message-prometheus
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30009
  selector:
    name: prometheus-pod
    app: message-broker