apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  labels:
    name: prometheus-deployment
    app: message-broker
spec:
  selector:
    matchLabels:
      name: prometheus-pod
      app: message-broker
  replicas: 1
  template:
    metadata:
      name: prometheus-pod
      labels:
        name: prometheus-pod
        app: message-broker
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--storage.tsdb.retention=20d'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf

        - name: prometheus-storage-volume
          emptyDir: { }